name: Build, Push Docker Image and Deploy to Render

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # felix850l
          password: ${{ secrets.DOCKER_PASSWORD }}   # PAT con permisos write/delete

      - name: Build Docker image with tags
        run: |
          docker build -t felix850l/ansible-docker-lab:latest \
                       -t felix850l/ansible-docker-lab:${{ env.SHA_SHORT }} \
                       -t felix850l/ansible-docker-lab:${{ env.DATE }} .

      - name: Push Docker images
        run: |
          docker push felix850l/ansible-docker-lab:latest
          docker push felix850l/ansible-docker-lab:${{ env.SHA_SHORT }}
          docker push felix850l/ansible-docker-lab:${{ env.DATE }}

      - name: Trigger Render deploy (deploy hook)
        run: |
          curl -sS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}" -w "\nHTTP_STATUS:%{http_code}\n"
